# Mission 1

![](https://i.imgur.com/Ax3pp2A.png)


Create a "fruit" dataframe that reflects the above example **using a list** data structure

[This resource could help you](https://datatofish.com/list-to-dataframe/).

In [1]:
import pandas as pd

In [3]:
fruit = pd.DataFrame([[30, 21]], columns=["Apples", "Bananas"])

fruit

   Apples  Bananas
0      30       21

# Mission 2

Create a "fruit_vendors" dataframe that reflects the below example **using a dictionary** data structure

![](https://i.imgur.com/CHPn7ZF.png)

[This resource could help you.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html)

In [19]:
fruit_vendors = pd.DataFrame({"Apples": [30, 41], "Bananas": [21, 34]})

fruit_vendors

   Apples  Bananas
0      30       21
1      41       34

# Mission 3

Use a loop to display the values from each column in the dataframe from mission 2.

[This resource could help you](https://www.w3schools.com/python/pandas/ref_df_items.asp)

In [20]:
for col, values in fruit_vendors.items():
    print(f"{col}: {values.tolist()}")

Apples: [30, 41]
Bananas: [21, 34]

# Mission 4

Delete the first row of the dataframe from mission 2

[This resource could help you.](https://sparkbyexamples.com/pandas/pandas-drop-first-row-of-dataframe/#google_vignette)

In [21]:
fruit_vendors.drop(index=0, inplace=True, errors="ignore")

fruit_vendors

   Apples  Bananas
1      41       34

# Mission 5

Delete the first column from the dataframe from mission 2.

In [ ]:
fruit_vendors.drop(columns=fruit_vendors.columns[0], inplace=True)

fruit_vendors