# Mission 1

Display the following information [for this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user).
- The last 5 rows
- The first 5 rows
- The type of each column

Note : start coding something by typing `pd.read_csv()` and explore the different options available, especially the `sep` parameter.

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user"

csv = pd.read_csv(
    url,
    sep="|",
    header=None,
    names=["id", "age", "genre", "emploi", "code postal"]
)

display(csv.tail())
display(csv.head())
csv.dtypes

# Mission 2

Display the first 10 rows [in the following file](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv)

In [9]:
url = "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv"

csv = pd.read_csv(
    url,
)

csv.head(10)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe

Set the "country" column as the index for the dataframe, using `set_index` method.

In [15]:
if csv.index.name != "country":
    csv = csv.set_index("country")

csv.head(10)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa
Antigua & Barbuda,102,128,45,4.9,North America
Argentina,193,25,221,8.3,South America
Armenia,21,179,11,3.8,Europe
Australia,261,72,212,10.4,Oceania
Austria,279,75,191,9.7,Europe

# Mission 3

Access the values of the row for **Zimbabwe** (use the index value)

In [17]:
csv.loc["Zimbabwe"]

beer_servings                       64
spirit_servings                     18
wine_servings                        4
total_litres_of_pure_alcohol       4.7
continent                       Africa
Name: Zimbabwe, dtype: object

# Mision 4

Display only the "continent" column value for the country **Zimbabwe**.

In [19]:
csv.loc["Zimbabwe", "continent"]

'Africa'

# Mission 5

Rename the columns [of this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv), try using the following 2 different methods to achieve this:
- Setting column names directly when reading the file
- Editing after creating the dataframe ([This resource could be useful](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html))

In [ ]:
url = "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv"

csv = pd.read_csv(
    url,
    header=0,
    names=["Ville", "Couleurs", "Forme", "Etat", "Heure"]
)

csv.head()

In [ ]:
csv = pd.read_csv(url)

csv = csv.rename(columns={"City": "Ville", "Colors Reported": "Couleurs", "Shape Reported": "Forme", "State": "Etat", "Time": "Heure"})

csv.head()

# Mission 6

Select the first 3 rows and all the columns of the dataframe using iloc

In [24]:
csv.iloc[0:3,:]

         Ville         Couleurs           Forme   Etat            Heure
0         City  Colors Reported  Shape Reported  State             Time
1       Ithaca              NaN        TRIANGLE     NY   6/1/1930 22:00
2  Willingboro              NaN           OTHER     NJ  6/30/1930 20:00

# Mission 7

Achieve the same result as in mission 6 by using loc

In [28]:
csv.loc[0:2]

         Ville         Couleurs           Forme   Etat            Heure
0         City  Colors Reported  Shape Reported  State             Time
1       Ithaca              NaN        TRIANGLE     NY   6/1/1930 22:00
2  Willingboro              NaN           OTHER     NJ  6/30/1930 20:00