In [1]:
import pandas as pd

### Welcome to the Apply Challenge

In [2]:
link = 'https://raw.githubusercontent.com/chriszapp/datasets/main/books.csv'
books = pd.read_csv(link, nrows = 13)
books.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

In [3]:
# Firstly, have a look at the dataset
books.info()
books.describe()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bookID              13 non-null     int64
 1   title               13 non-null     str
 2   authors             13 non-null     str
 3   average_rating      13 non-null     float64
 4   isbn                13 non-null     str
 5   isbn13              13 non-null     int64
 6   language_code       13 non-null     str
 7     num_pages         13 non-null     int64
 8   ratings_count       13 non-null     int64
 9   text_reviews_count  13 non-null     int64
 10  publication_date    13 non-null     str
 11  publisher           13 non-null     str
dtypes: float64(1), int64(5), str(6)
memory usage: 1.3 KB

,bookID,average_rating,isbn13,num_pages,ratings_count,text_reviews_count
count,13.000000,13.000000,1.300000e+01,13.000000,1.300000e+01,13.000000
mean,10.230769,4.390769,9.780608e+12,900.230769,5.519447e+05,8384.000000
std,6.193462,0.266598,2.974156e+08,988.381350,9.428682e+05,13313.199847
min,1.000000,3.740000,9.780345e+12,6.000000,1.900000e+01,1.000000
25%,5.000000,4.220000,9.780440e+12,352.000000,3.628000e+03,244.000000
50%,10.000000,4.380000,9.780440e+12,652.000000,2.824200e+04,460.000000
75%,14.000000,4.560000,9.780739e+12,815.000000,2.495580e+05,9396.000000
max,21.000000,4.780000,9.781400e+12,3342.000000,2.339585e+06,36325.000000

In [4]:
# Mission 1: use apply to create a new column called 'reviews_opinion': if the ratings is between 4.5 and 5, the reviews_opinion is 'very good';
# if the rating is between 4 and 4.5, the reviews_opinion is 'good'; if the rating is between 3 and 4, the reviews_opinions will be 'neutral';
# if the rating is up to 3 the reviews_opinion is going to be 'bad'

# Add your code here
def opinion(rating):
    if rating >= 4.5:
        return 'very good'
    elif rating >= 4:
        return 'good'
    elif rating >= 3:
        return 'neutral'
    else:
        return 'bad'

books['reviews_opinion'] = books['average_rating'].apply(opinion)
books[['title', 'average_rating', 'reviews_opinion']]

,title,average_rating,reviews_opinion
0,Harry Potter and the Half-Blood Prince (Harry ...,4.57,very good
1,Harry Potter and the Order of the Phoenix (Har...,4.49,good
2,Harry Potter and the Chamber of Secrets (Harry...,4.42,good
3,Harry Potter and the Prisoner of Azkaban (Harr...,4.56,very good
4,Harry Potter Boxed Set Books 1-5 (Harry Potte...,4.78,very good
5,"Unauthorized Harry Potter Book Seven News: ""Ha...",3.74,neutral
6,Harry Potter Collection (Harry Potter #1-6),4.73,very good
7,The Ultimate Hitchhiker's Guide: Five Complete...,4.38,good
8,The Ultimate Hitchhiker's Guide to the Galaxy ...,4.38,good
9,The Hitchhiker's Guide to the Galaxy (Hitchhik...,4.22,good
10,The Hitchhiker's Guide to the Galaxy (Hitchhik...,4.22,good
11,The Ultimate Hitchhiker's Guide (Hitchhiker's ...,4.38,good
12,A Short History of Nearly Everything,4.21,good

In [5]:
# Mission 2: using apply with a function, create a column with the number of authors per book
# (note that in the column 'authors', each name of the author is divided with the character '/')

# Add your code here
def nombre_auteurs(auteurs):
    return len(auteurs.split('/'))

books['nb_authors'] = books['authors'].apply(nombre_auteurs)
books[['authors', 'nb_authors']]

                       authors  nb_authors
0   J.K. Rowling/Mary GrandPré           2
1   J.K. Rowling/Mary GrandPré           2
2                 J.K. Rowling           1
3   J.K. Rowling/Mary GrandPré           2
4   J.K. Rowling/Mary GrandPré           2
5       W. Frederick Zimmerman           1
6                 J.K. Rowling           1
7                Douglas Adams           1
8                Douglas Adams           1
9                Douglas Adams           1
10   Douglas Adams/Stephen Fry           2
11               Douglas Adams           1
12                 Bill Bryson           1

In [6]:
# Mission 3: rewrite the same task as Mission 2 using the lamdba function

# Add your code here
books['nb_authors'] = books['authors'].apply(lambda auteurs: len(auteurs.split('/')))
books[['authors', 'nb_authors']]

                       authors  nb_authors
0   J.K. Rowling/Mary GrandPré           2
1   J.K. Rowling/Mary GrandPré           2
2                 J.K. Rowling           1
3   J.K. Rowling/Mary GrandPré           2
4   J.K. Rowling/Mary GrandPré           2
5       W. Frederick Zimmerman           1
6                 J.K. Rowling           1
7                Douglas Adams           1
8                Douglas Adams           1
9                Douglas Adams           1
10   Douglas Adams/Stephen Fry           2
11               Douglas Adams           1
12                 Bill Bryson           1

In [7]:
# Mission 4: create a column 'comment_ration'.
# Use the columns 'ratings_count' and 'text_reviews_count' to calculate the percentage of how many text review per reviews are per book:
# percentage = text / reviews * 100
# Use the mathematical operations between columns

# Add your code here
books['comment_ratio'] = books['text_reviews_count'] / books['ratings_count'] * 100
books[['ratings_count', 'text_reviews_count', 'comment_ratio']]

    ratings_count  text_reviews_count  comment_ratio
0         2095690               27591       1.316559
1         2153167               29221       1.357117
2            6333                 244       3.852834
3         2339585               36325       1.552626
4           41428                 164       0.395868
5              19                   1       5.263158
6           28242                 808       2.860987
7            3628                 254       7.001103
8          249558                4080       1.634890
9            4930                 460       9.330629
10           1266                 253      19.984202
11           2877                 195       6.777894
12         248558                9396       3.780204

In [8]:
# Mission 5: obtain the same result of Mission 4 using apply with a function.
# Try both methods to apply to the whole dataset and apply to selected columns

# Add your code here
def ratio(ligne):
    return ligne['text_reviews_count'] / ligne['ratings_count'] * 100

books['comment_ratio'] = books.apply(ratio, axis=1)

books['comment_ratio'] = books[['ratings_count', 'text_reviews_count']].apply(ratio, axis=1)
books[['ratings_count', 'text_reviews_count', 'comment_ratio']]

    ratings_count  text_reviews_count  comment_ratio
0         2095690               27591       1.316559
1         2153167               29221       1.357117
2            6333                 244       3.852834
3         2339585               36325       1.552626
4           41428                 164       0.395868
5              19                   1       5.263158
6           28242                 808       2.860987
7            3628                 254       7.001103
8          249558                4080       1.634890
9            4930                 460       9.330629
10           1266                 253      19.984202
11           2877                 195       6.777894
12         248558                9396       3.780204

In [9]:
# Mission 6: obtain the same result of Mission 5 using apply lambda
# Try both methods to apply to the whole dataset and apply to selected columns

# Add your code here
books['comment_ratio'] = books.apply(lambda ligne: ligne['text_reviews_count'] / ligne['ratings_count'] * 100, axis=1)

books['comment_ratio'] = books[['ratings_count', 'text_reviews_count']].apply(
    lambda ligne: ligne['text_reviews_count'] / ligne['ratings_count'] * 100, axis=1)
books[['ratings_count', 'text_reviews_count', 'comment_ratio']]

    ratings_count  text_reviews_count  comment_ratio
0         2095690               27591       1.316559
1         2153167               29221       1.357117
2            6333                 244       3.852834
3         2339585               36325       1.552626
4           41428                 164       0.395868
5              19                   1       5.263158
6           28242                 808       2.860987
7            3628                 254       7.001103
8          249558                4080       1.634890
9            4930                 460       9.330629
10           1266                 253      19.984202
11           2877                 195       6.777894
12         248558                9396       3.780204

In [10]:
# Mission 7: extract the year from the publication_date column. How many years of publications are recorded in this dataset? Which are them?
# Add your code here
books['year'] = books['publication_date'].apply(lambda date: int(date.split('/')[-1]))

print("Nombre d'années :", books['year'].nunique())
print('Années :', sorted(books['year'].unique().tolist()))

Nombre d'années : 6
Années : [1996, 2002, 2003, 2004, 2005, 2006]